services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: artemstasyuk
      POSTGRES_PASSWORD: Croatoan00404
      POSTGRES_DB: la_bella_ferdinanda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: stasyukartem2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Croatoan00404
    ports:
      - "8000:80"
    depends_on:
      - postgres
# TODO: CHECK IF IMAGE IS CORRECT
  java-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: