# Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/la_bella_ferdinanda
spring.datasource.username=postgres
spring.datasource.password=postgres

# Fly.io
# spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}

# BETTER SQL GENERATION FOR POSTGRESQL
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Disable Thymeleaf template check
spring.thymeleaf.check-template-location=false

# HIBERNATE DDL AUTO
spring.jpa.hibernate.ddl-auto=update

server.error.include-binding-errors=always
server.port=8080
server.servlet.context-path=/api

# JWT CONFIGURATION
jwt.secret=labellaferdinanda
jwt.expiration=3600000

# Image Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB